services:
  gopher:
    build:
      context: ../..
      dockerfile: smallweb/gopher/Dockerfile
    ports:
      - "7070:7070"
    volumes:
      - ../../_gopher:/var/gopher:ro
    restart: unless-stopped
